# Generated by Django 3.2.24 on 2024-08-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='photo',
            field=models.ImageField(default='school/class/photo.jpg', upload_to='school/class'),
        ),
    ]
